SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY 
FROM EMPLOYEE E JOIN DEPARTMENT D
ON E.DEPARTMENTID = D.ID
WHERE(SELECT COUNT(DISTINCT(SALARY)) FROM EMPLOYEE E2 WHERE E2.SALARY > 
      E.SALARY AND E2.DEPARTMENTID = D.ID) <3 
      ORDER BY E.NAME, E.SALARY DESC
      
      
