SELECT N.NAME AS EMPLOYEE, D.NAME FROM NEWEMPLOYEE N, DEPARTMENTNEW D
WHERE N.DEPARTMENTID = D.ID
AND N.SALARY = (SELECT MAX(SALARY) FROM NEWEMPLOYEE T 
                WHERE T.DEPARTMENTID = D.ID)
                
            
